description:
  beammap_dasha configuration file
inputs:
  #- path: /Users/mmccrackan/toltec/data/lmt/220616/3c279/
  #- path: /Users/mmccrackan/toltec/temp/3c345/redu_3c345_toast/redu00/
  - path: /data/work_toltec/220629/redu/
    description: Path to search for obsnums
